### PR TITLE
fix: off-by-one error when drawing detour point markers

### PR DESCRIPTION
**Pull request by lemald**
Asana ticket: slight follow-up on [⚙️🚧 Click on the map to draw, click on waypoints, and click on route to end](https://app.asana.com/0/1148853526253420/1206038957525487/f)

### CODE REVIEW

**Comment by joshlarson** [comment]
Is there any convenient way to test this?

**Review by firestack — APPROVED** [review]

**Comment by firestack** [comment]
> Is there any convenient way to test this?

Oops, didn't mean to overshadow this with my approval, seconded.

**Comment by lemald** [comment]
> > Is there any convenient way to test this?
> 
> Oops, didn't mean to overshadow this with my approval, seconded.

I'll look into this before merging!

**Comment by lemald** [comment]
Added a test in 4452c3c0. I confirmed that with the old version of the code in `detourMap.tsx` the test fails.

**Review by joshlarson — APPROVED** [review]

**Pull request merged**
