### PR TITLE
Declare that this site is "app capable"

### PR DESCRIPTION
**Pull request by arkadyan**
This will let us launch it from the desktop without a tab bar.

### CODE REVIEW

**Comment by skyqrose** [comment]
This is all the stuff in Glides for being "app capable". It's a lot more than these two lines. Do we need to do any more of it here?
```
    <link rel="apple-touch-icon" sizes="180x180" href="<%= static_path(@conn, "/favicons/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= static_path(@conn, "/favicons/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= static_path(@conn, "/favicons/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= static_path(@conn, "/site.webmanifest") %>">
    <link rel="mask-icon" color="#0a3355" href="<%= static_path(@conn, "/favicons/safari-pinned-tab.svg") %>">
    <link rel="shortcut icon" href="<%= static_path(@conn, "/favicons/favicon.ico") %>">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="msapplication-config" content="<%= static_path(@conn, "/favicons/browserconfig.xml") %>">
    <meta name="theme-color" content="#ffffff">
```

**Comment by arkadyan** [comment]
@skyqrose that list is helpful, thanks. The most applicable things that jump out at me is the icon stuff. I'm thinking I'll make a new ticket for that for creating an icon and then implementing those bits. I'm thinking we can skip the Windows Mobile stuff for the moment since the focus is the Android tablets. Does that all seem right and am I missing anything?

**Comment by arkadyan** [comment]
Ticket for the icon work: https://app.asana.com/0/1112935048846093/1119875758955533

**Comment by skyqrose** [comment]
Assuming you've tried this from the tablet?

**Comment by arkadyan** [comment]
Yep, it makes the saved site work like an app on the tablet.

**Pull request merged**
