### PR TITLE
Make swings view column headers sticky

### PR DESCRIPTION
**Pull request by phildarnowsky**

### CODE REVIEW

**Review by lemald — APPROVED** [review]
Looks good to me! We should just make sure to QA on tablet and mobile if you haven't done so already.

**Comment by phildarnowsky** [comment]
> We should just make sure to QA on tablet and mobile if you haven't done so already.

It's the swings view--desktop only, right?

**Comment by lemald** [comment]
> > We should just make sure to QA on tablet and mobile if you haven't done so already.
> 
> It's the swings view--desktop only, right?

Nah - in fact, if I had to guess, most users are on tablet, and we put together specific mobile designs and CSS for it.

**Comment by phildarnowsky** [comment]
@lemald looks good on the inspector tablet, iPhone, and Android phone.

**Pull request merged**
