### PR TITLE
User location dot

### PR DESCRIPTION
**Pull request by lemald**
Asana ticket: [Implement location dot](https://app.asana.com/0/1148853526253420/1205411312261325/f)

Screenshot 2023-09-22 at 11 22 24

### CODE REVIEW

**Review by firestack — APPROVED** [review]
So far I don't really have anything else, it's working well on my end and I've not needed to make any changes to the code introduced here. 
though I did need to create wrapper component for the useGeolocation hook so I could use it conditionally, I don't think that belongs in this PR though.

**Review by firestack — APPROVED** [review]
So far I don't really have anything else, it's working well on my end and I've not needed to make any changes to the code introduced here. 
though I did need to create wrapper component for the useGeolocation hook so I could use it conditionally, I don't think that belongs in this PR though.

**Comment by firestack** [comment]
Oh, before merging this, should we merge the chromatic branch first?

**Comment by lemald** [comment]
> Oh, before merging this, should we merge the chromatic branch first?

I think we should wait on that while that's up in the air. I'll just change the base branch on this PR before merging.

**Comment by firestack** [comment]
> > Oh, before merging this, should we merge the chromatic branch first?
> 
> I think we should wait on that while that's up in the air. I'll just change the base branch on this PR before merging.

Sounds good, just wanted to make sure those changes were intentionally reviewed before merge and wouldn't accidentally get merged to master.

**Pull request merged**
