### PR TITLE
feat: Update activate detour modal to match hi-fi designs

### PR DESCRIPTION
**Pull request by joshlarson**
# Before

Screenshot 2024-09-26 at 11 11 21 AM

# After

Screenshot 2024-09-26 at 11 11 36 AM

---

Asana Ticket: https://app.asana.com/0/1148853526253420/1208390832296805/f

### CODE REVIEW

**Review by hannahpurcell — COMMENTED** [review]
Great! I like having the StepSubtitle. 

Some things to consider: 
- I think there needs to be a close button in the top right of the modal (in addition to the cancel button)
- Seems like there needs to be more padding between the radio options
- Validation needs to be done. Do that here?

**Comment by joshlarson** [comment]
@hannahpurcell I think I've addressed your feedback, and this is ready for another 👀

**Comment by hannahpurcell** [comment]
> I was honestly thinking that the easiest way to validate would be to ship to skate-dev and have Brian do validation there, with any fixes being fast-follow PR's.

Oh I meant form validation! I should have attached [a link](https://www.figma.com/design/XGmmwVROXdOvnWtJeUFC50/Skate-%7C-Unplanned-Detours-%7C-Handoff?node-id=3678-2705&t=RFMXKhBGPaGLeWyR-4)

**Review by firestack — APPROVED** [review]

**Comment by joshlarson** [comment]
Ooohhhh

I left that out because I'm pretty sure that's an impossible state to get to. The `Next` button is unclickable when nothing is selected, but the only way to get the validation errors is by clicking on it when nothing is selected.

**Comment by firestack** [comment]
> I left that out because I'm pretty sure that's an impossible state to get to. The `Next` button is unclickable when nothing is selected, but the only way to get the validation errors is by clicking on it when nothing is selected.

Oh oops sorry I didn't see @hannahpurcell's review. IIRC disabled buttons are a bad UX practice and they should do something when clicked and provide a message, so I'm pretty certain we should do this, if only to satisfy the designs. I personally like it being in the disabled state, but can we do that in addition to showing a error state?

**Comment by joshlarson** [comment]
I talked a bit with Hannah about this in our 1:1.

I'd prefer to merge this as-is, and treat validation as a follow-up, especially since I'm uncertain about the level-of-effort associated with making a disabled button clickable, and treat validation (error feedback, disabled/enabled buttons, etc) as a follow-up.

**Review by firestack — APPROVED** [review]

**Pull request merged**
