### PR TITLE
Open swings view to all

### PR DESCRIPTION
**Pull request by phildarnowsky**

### CODE REVIEW

**Comment by lemald** [comment]
@phildarnowsky there are also a couple of references to the flag in `tabBar.test.tsx`, including a test specifically to make sure that the toggle works that can probably be removed.

**Comment by phildarnowsky** [comment]
@lemald removed those references

**Review by lemald — APPROVED** [review]
Looks good to me! I guess just make sure it all still works on dev if the environment variables are removed, and don't forget to followup to change the ECS configuration for dev-blue.

**Comment by phildarnowsky** [comment]
@lemald yeah I have a separate infra PR to do the ECS bit

**Pull request merged**
