### PR TITLE
rotate VPP icon to match orientation on ladder

### PR DESCRIPTION
**Pull request by skyqrose**
Asana Task: [Orient triangle in VPP to match the ladder](https://app.asana.com/0/1148853526253426/1126875696911113)

Screen Shot 2020-01-15 at 17 28 28
Screen Shot 2020-01-15 at 17 28 39

### CODE REVIEW

**Comment by skyqrose** [comment]
I added one test for shuttles, but codecov is still failing because I don't test both a left-facing bus and a right-facing bus. Can you force merge?

**Comment by arkadyan** [comment]
@skyqrose is there a reason not to just test both?

**Comment by skyqrose** [comment]
It would be verbose without adding any additional safety.

**Comment by arkadyan** [comment]
@skyqrose verbosity is what test code is all about.

I think if you wanted to write unit tests that would work too, but I agree with Codecov that this code should be completely tested.

**Pull request merged**
