### PR TITLE
And now start backfiller

### PR DESCRIPTION
**Pull request by phildarnowsky**

### CODE REVIEW

**Comment by phildarnowsky** [comment]
@lemald this PR is to restore the backfiller once the migrations are run

**Comment by lemald** [comment]
@phildarnowsky I think this would probably be a good place to also include the fix to `default_name` from #983 since that one isn't going to get merged.

**Comment by phildarnowsky** [comment]
@lemald fixed the `default_name`

**Comment by lemald** [comment]
@phildarnowsky I think this also needs to be rebased to remove the first commit, which is actually the commit from the other PR?

**Comment by phildarnowsky** [comment]
@lemald this should do it--just have to remember not to merge it until we actually deploy the other, which is now merged

**Review by lemald — APPROVED** [review]
Looks good to me with the caveat you gave about the deploy process. 👍

**Pull request merged**
