### PR TITLE
Configure prod site to redirect from http to https

### PR DESCRIPTION
**Pull request by arkadyan**
Asana ticket: [Set up a redirect from http to https](https://app.asana.com/0/1112935048846093/709916117691678)

### CODE REVIEW

**Comment by arkadyan** [comment]
@paulswartz does the port still need to be open for this on the dev server?

**Comment by arkadyan** [comment]
@skyqrose yep, good call. Added that.

**Comment by paulswartz** [comment]
I'd actually have said no: API requests to the wrong URL should fail, as they're automated. The reason for redirecting is to allow people to type `skate-dev.mbtace.com` into their browser and have it work: that's not a concern for the API side.

**Comment by arkadyan** [comment]
@paulswartz Ok, fair. I can pull that back out.

**Pull request merged**
