### PR TITLE
chore(dependabot/roundup/hex+npm): merge dependabot PR's

### PR DESCRIPTION
**Pull request by firestack**
## Summary
We have a lot of dependabot PR's open, most seem to be passing, as well as this roundup of all the updated packages have passed CI. 

Given we should be able to trust CI, I don't see a reason to not update, despite some major semver changes, tests are still passing.

These packages are not included
- > Bumps [sentry](https://github.com/getsentry/sentry-elixir) from 7.2.4 to 8.0.6.
- > Bumps [csv](https://github.com/beatrichartz/csv) from 2.4.1 to 3.0.5.

## Details
For each `refspec`
```
: set refspec refs/remotes/origin/dependabot/hex
: set refspec refs/remotes/origin/dependabot/npm_and_yarn
```
I ran the following command
```
: for ref in (git for-each-ref $refspec --format='%(refname:short)')
: 	git merge $ref --no-edit -s ours --no-ff 
: end
```

### CODE REVIEW

**Comment by lemald** [comment]
@firestack thanks a bunch for putting this together! Always good to try to keep on top of dependency updates.

Even though CI passes I'd definitely recommend deploying to a dev environment just as a quick check to make sure everything starts up and doesn't cause obvious errors.

Regarding Sentry, there is are some [particular changes in the upgrade guide](https://gist.github.com/mitchellhenke/dce120a5515565076b13962ee0be749b#replace-sentryplug-and-sentryphoenixendpoint) that we'll probably want to do.

For CSV, the [upgrade instructions](https://github.com/beatrichartz/csv/blob/main/CHANGELOG.md#upgrading-from-2x) don't include anything obvious that I think we'll need to address - as long as the application starts up and parses the schedule data without new errors / warnings I think we're good to go.

**Comment by firestack** [comment]
@lemald I tried to spend just a few minutes on this

We have one thing in `csv` that needs to be changed, and I think I'm gonna drop sentry and manage that in a separate PR :c

**Comment by lemald** [comment]
> @lemald I tried to spend just a few minutes on this
> 
> We have one thing in `csv` that needs to be changed, and I think I'm gonna drop sentry and manage that in a separate PR :c

Totally fair! Can you just do me a favor and add a quick ticket to our tech cleanup board to do the Elixir Sentry upgrade?

**Comment by firestack** [comment]
> Totally fair! Can you just do me a favor and add a quick ticket to our tech cleanup board to do the Elixir Sentry upgrade?

👍🏻 Opened [Elixir Sentry update Asana ticket](https://app.asana.com/0/1202526086845554/1203569104343196)

**Comment by firestack** [comment]
Tests are failing due to some removed features around field stripping in CSV, dropping that PR commit as well. Will open a ticket.

**Review by lemald — APPROVED** [review]
Thanks again! LGTM if you do a quick deploy to dev-[blue|green] first just to make sure the app starts up all right.

**Comment by firestack** [comment]
Logs in splunk seem fine, web view is responsive and working. 
Unsure if there's something I'm missing, but LGTM.

**Comment by lemald** [comment]
> Logs in splunk seem fine, web view is responsive and working. Unsure if there's something I'm missing, but LGTM.

That's all I had in mind to check! :shipit:

**Comment by firestack** [comment]
Resolves #1679 #1680 #1682 #1695 #1709 #1724 #1731 #1775 #1777 #1793 #1801 #1818 #1819 #1827 #1837 #1838 #1839 #1841

**Pull request merged**
